---
- name: Secure Python Secrets
  hosts: localhost

  tasks:
    - name: Run my python script
      register: my_output
      changed_when: my_output.rc != 0
      ansible.builtin.script:
        cmd: scripts/my_secret.py
