---
- name: Secure Python Secrets
  hosts: all:!localhost
  vars_files:
    - files/secrets.yml

  environment:
    DYNATRACE_API_KEY: "{{ dynatrace_api_key }}"

  tasks:

    - name: Run my python script
      register: my_output
      changed_when: my_output.rc != 0
      ansible.builtin.script:
        cmd: scripts/my_secret.py
